In [1]:
#pca algorithm from https://www.dominicswaine.com/code/ain/tutorial-6
import matplotlib.pyplot as plt
import numpy as np

In [2]:
k=2
X=np.array([
    [4,2,3],
    [6,1,3],
    [4,2,5],
    [7,8,3]
])
print(X.shape)

(4, 3)


In [4]:
print("Step 1 (compute mean row vector)")
meanrow =np.zeros((1,X.shape[1]))
for i in range(X.shape[1]):
    meanrow[0,i]= sum(X[:,i]/X.shape[0])
print(meanrow)


Step 1 (compute mean row vector)
[[5.25 3.25 3.5 ]]


In [5]:
print("Step 2 (compute mean row matrix)")
meanrowmatrix=np.ones((X.shape[0],1))* meanrow
print(meanrowmatrix)

Step 2 (compute mean row matrix)
[[5.25 3.25 3.5 ]
 [5.25 3.25 3.5 ]
 [5.25 3.25 3.5 ]
 [5.25 3.25 3.5 ]]


In [6]:
print("Step 3 (substract mean)")
B= X-meanrowmatrix
print(B)

Step 3 (substract mean)
[[-1.25 -1.25 -0.5 ]
 [ 0.75 -2.25 -0.5 ]
 [-1.25 -1.25  1.5 ]
 [ 1.75  4.75 -0.5 ]]


In [7]:
print("Step 4 (compute covariance matrix of rows of B)")
Cov=B.T.dot(B)
print(Cov)

Step 4 (compute covariance matrix of rows of B)
[[ 6.75  9.75 -2.5 ]
 [ 9.75 30.75 -2.5 ]
 [-2.5  -2.5   3.  ]]


In [8]:
print("Step 5 (compute the k lagest eigenvectors)")
eigenValues,eigenVectors=np.linalg.eig(Cov)
idx=eigenValues.argsort()[::-1]
eigenValues=eigenValues[idx]
eigenVectors=eigenVectors[:,idx]
print("eigenVectors")
print(eigenVectors)
print("eigenValues",eigenValues)
print(f'Check if Av1=lambda1 v1:\nAv1 ={Cov.dot(eigenVectors[:,0])}\nlambda1 v1={eigenValues[0]*eigenVectors[:,0]}')
print(f'Check if Av2=lambda2 v2:\nAv2 ={Cov.dot(eigenVectors[:,1])}\nlambda2 v2={eigenValues[1]*eigenVectors[:,1]}')


Step 5 (compute the k lagest eigenvectors)
eigenVectors
[[-0.33749161 -0.70668821  0.62184499]
 [-0.93589997  0.32274925 -0.14115302]
 [ 0.10094883  0.62962267  0.77031463]]
eigenValues [34.53557041  4.52448037  1.43994922]
Check if Av1=lambda1 v1:
Av1 =[-11.6554651  -32.32183924   3.48632542]
lambda1 v1=[-11.6554651  -32.32183924   3.48632542]
Check if Av2=lambda2 v2:
Av2 =[-3.19739691  1.46027263  2.84871541]
lambda2 v2=[-3.19739691  1.46027263  2.84871541]


In [9]:
print("Step 6 (compute W)")
W=eigenVectors[:,0:k]
print(W)


Step 6 (compute W)
[[-0.33749161 -0.70668821]
 [-0.93589997  0.32274925]
 [ 0.10094883  0.62962267]]


In [10]:
print("Step7 (project)")
for i in range(X.shape[0]):
    transformed= W.T.dot(X[ i, :])
    print("transformed =", i," ", transformed)


Step7 (project)
transformed = 0   [-2.91891987 -0.29238632]
transformed = 1   [-2.65800311 -2.02851198]
transformed = 2   [-2.71702221  0.96685901]
transformed = 3   [-9.54679449 -0.47595547]
